[workspace]
members = [
    "canister/api",
    "canister/impl",
]
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
candid = "0.10.6"
ic-cdk = "0.13.2"
serde = "1.0.197"
serde_bytes = "0.11.14"
