[package]
name = "email_sender_aws_lambda"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config.workspace = true
aws_lambda_events = { workspace = true, features = ["sqs"] }
aws-sdk-sesv2.workspace = true
lambda_runtime.workspace = true
magic_links.path = "../../../libraries/magic_links"
rand.workspace = true
rsa.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
