on:
  push:
    branches:
      - master

name: Build caches

jobs:
  build_all_debug:
    name: Build in debug mode
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.79.0
          override: true
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "build-debug"
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --tests
