[package]
name = "sign_in_with_email_canister"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candid.workspace = true
serde.workspace = true
serde_bytes.workspace = true
